services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./src/main/resources/secret.properties
    volumes:
      - ./backup:/backup
      - ./logs:/logs
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      NTFY_USER: ${NTFY_USER}
      NTFY_PASSWORD: ${NTFY_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      APPLE_REDIRECT_URI: ${APPLE_REDIRECT_URI}
      APPLE_TEAM_ID: ${APPLE_TEAM_ID}
      APPLE_KEY_ID: ${APPLE_KEY_ID}
      APPLE_PRIVATE_KEY: ${APPLE_PRIVATE_KEY}
  database:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    volumes:
      - ./postgresql:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}